### ISSUE TITLE
Enhancement: generated files (logs/config) one or two directories (helps with docker integration)

### ISSUE THREAD

**Issue by blackbarn** [d8ahazard/Phlex#12]
It would be interesting to have docker integration.  I would only suggest one change in the project to  make integration easier:

1. All runtime in/out (log files, configs) to be in one or two directories (vs individual files in root), this way folks can link that folder to their host for persistence.

For anyone's reference I've set this up manually for now.

https://hub.docker.com/r/blackbarn/phlex/ (a Dockerfile could be added to the repo, and connected to dockerhub to auto-build officially)

Built the image with a custom 000-default site & ports.conf to change the port to 8080 -- I'm behind a reverse proxy via Traefik so i needed to do this.

Phlex has runtime output files. Currently written to the root www folder. I wanted to persist these so i had to manually set up mappings.

example compose file:

```
phlex:
  extends:
    file: ../common.yml
    service: base
  build: ./phlex
  hostname: phlex
  container_name: phlex
  volumes:
    - /opt/services/phlex/config/config.ini.php:/var/www/html/config.ini.php:rw
    - /opt/services/phlex/config/commands.php:/var/www/html/commands.php:rw
    - /opt/services/phlex/config/Phlex.log:/var/www/html/Phlex.log:rw
    - /opt/services/phlex/config/PhlexREQ.log:/var/www/html/PhlexREQ.log:rw
    - /opt/services/phlex/config/Phlex_error.log:/var/www/html/Phlex_error.log:rw
  labels:
    - traefik.frontend.passHostHeader=true
    - traefik.port=8080
```

Thanks!
